version: '3'

networks:
  default:
    external:
      name: hybris_network

volumes:
  commerce_db: {}
  cpq_db: {}

services:
  commerce_db:
    image: mysql:latest
    container_name: "commerce_db"
    volumes:
      - commerce_db:/var/lib/mysql
    ports:
      - "9305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nimda
      - MYSQL_USER=hybris
      - MYSQL_PASSWORD=hybris
      - MYSQL_DATABASE=commerce_db

  cpq_db:
    image: mysql:latest
    container_name: "cpq_db"
    volumes:
      - cpq_db:/var/lib/mysql
    ports:
      - "9306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nimda
      - MYSQL_USER=hybris
      - MYSQL_PASSWORD=hybris
      - MYSQL_DATABASE=hybris_cpq

  hybris:
    build: ./compose/hybris
    container_name: hybris
    ports:
      - "9991:9001"
      - "9992:9002"
    command: ./hybrisserver.sh
